### PR TITLE
Its Syntax 64!

### PR DESCRIPTION
**Pull request by moiez0**
Here is my updated version of the Jarvis Assistant.

### CODE REVIEW

**Comment by moiez0** [comment]
Ignore the deleted stuff, I was moving a folder inside the scripts folder.

**Comment by moiez0** [comment]
Here is the latest ver of main.py:
https://github.com/Dipeshpal/Jarvis-Assisant/blob/12893d254b5f8b583d38c259195ba3fe67472117/scripts/main.py

And also just wanna explain what I added:
- Updated main.py
- I added a instructions file
- Made a library folder inside of the scripts folder for the mp3 player in main.py
That's all.

**Comment by Dipeshpal** [comment]
Can you please create a seperate branch then again do a pull request?

**Comment by Dipeshpal** [comment]
Great Job, please add readme if possible.

**Pull request merged**
